### ISSUE TITLE
Display of unicode-test.txt has error in some glyphs

### ISSUE THREAD

**Issue by plntyk** [Aetf/kmscon#11] opened 2018-08-24 14:11 UTC
docs/unicode-test.txt Line 3, first 13 symbols for example are internally rendered bigger and then
some small part of that rendered glyph is displayed: like some edge of a circle/square on other symbols (like emojis)

since kmscon uses Pango i checked in KDE, xfce4-terminal with

    pango-view --text="♉♊♋♌♍♎♏♐♑♒" --font="DejaVu Sans Mono"

Result: color emoji due to font replacement/missing glyphs (?) and correct size with font - rending by default should be cairo
However

    pango-view --backend=ft2 --text="♉a♊s♋d♌f♍♎♏♐♑♒" --font="DejaVu Sans Mono"

Result: larger black/white glyphs (similar to parts displayed in kmscon) but complete symbols but different symbol and "normal" font size.

````
/etc/kmscon/kmscon.conf 
font-name=DejaVu Sans Mono
font-size=16
vt=5
no-switchvt
````
beside some glyphs of docs/unicode-test.txt the following emojis exhibit the problem too for example:
````
😀😂🙀😈😇😤🙌🙈🙏
````

According to kmscon docs it uses freetype2 so it might be some issue with different fonts from that side?
Also, this might be "duplicate" of https://github.com/dvdhrm/kmscon/issues/133 

System: Arch Linux, Intel HD4000 integrated in CPU i7-3770

**Comment by plntyk** [comment] 2018-09-06 06:08
Done some additional testing with pango-view, ft2 and cairo backends, some fontconfig changes:
like custom
````FONTCONFIG_FILE=fonts.conf `FONTCONFIG_PATH=./ pango-view ........````
using 
````FC_DEBUG=<number>````
show that pango-view cairo backend can show "wrong" sizes if one disables/remove
````/etc/fonts/conf.d/10-scale-bitmap-fonts.conf````
IIRC the font-cache should be cleaned too between tests to make sure.

Using the shortcuts of kmscon ````--grab-zoom-in <grab>       [<Ctrl>Plus]
	                                  Shortcut to increase font size````
shows complete bitmap symbols on a ridiculous font-size.

For test/scripting notice that 'pango-view' can output to a picture file.

So "new" bitmap-fonts -- those that might have "CBDT Data Tables" in them -- and their scaling seems to be the culprit. Those color/picture fonts are probably going to stay and are developed even further: [Colorfonts](https://www.colorfonts.wtf/)
Checking of emoji/symbol content of a font was done with program "gucharmap" with setting "Only show glyph of this font"

**Temporary "workaround"** but with some bugs in character width too: use Symbola Font.
The Symbola Font is a more "normal" font and has exotic symbols and emojis like 🦖
but the Symbola raptor is incomplete too on : only the left half of the glyph is displayed.

**Comment by Aetf** [comment] 2018-09-06 21:13
Okay. So if I understand correctly, this is caused by some bitmap fonts not having correct scaling information with them? So it's not a bug in kmscon.

> the Symbola raptor is incomplete too on : only the left half of the glyph is displayed.

This might be a separate issue about the character width and which `wcwidth` implementation your shell and kmscon is using. See Aetf/libtsm#1.

I'm closing the issue and adding a wiki page documenting this. Feel free to add more to the wiki if you find out more :)

**Closed by Aetf** 2018-09-06 21:13 UTC
Labels: documentation, invalid

**Comment by plntyk** [comment] 2018-09-07 09:14
I extended documentation on unicode, colored glyphs, colored fonts and font formats and some test/bug issues in the wiki.

**Comment by Aetf** [comment] 2018-09-07 14:37
@plntyk Thank you so much!
